Napravljen server.js
FD-IT/CR_HUB pull request #10
Opened 2023-12-13 23:29 UTC by ilic25

Dodavanje server.js i instalacija Express.js zajedno sa nodemon

2023-12-13 23:29 UTC, ilic25 commented
Sve je testirano i pokrenuto lokalno

2023-12-14 09:21 UTC, markovicm668 requested changes
premesti ga samo iz foldera models u parent folder **cr hub**

2023-12-14 15:06 UTC, ilic25 commented
> premesti ga samo iz foldera models u parent folder **cr hub**

Ovako?

2023-12-14 21:08 UTC, markovicm668 approved these changes

2023-12-14 21:08 UTC, merged